name: Sync with upstream

on:
  schedule:
    - cron: "*/15 * * * *"  # Executa diariamente
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ConcatechOrg/black-flight-logistic
          token: "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"
          path: upstream
          fetch-depth: 0  

      - name: Checkout fork repository
        uses: actions/checkout@v2
        with:
          token: "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"
          path: fork
          fetch-depth: 0 

      - name: Sync upstream to fork
        run: |
          cd fork
          git remote add upstream ../upstream
          git fetch upstream
          git merge upstream/main --allow-unrelated-histories
          git push origin main
        env:
          GITHUB_TOKEN: "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"
