name: Sync with upstream

on:
  schedule:
    - cron: "*/15 * * * *"  # Executa diariamente
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ConcatechOrg/black-flight-logistic
          token: ${{ secrets.GITHUBACTION }}
          path: upstream

      - name: Checkout fork repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUBACTION }}
          path: fork

      - name: Sync upstream to fork
        run: |
          cd fork
          git remote add upstream ../upstream
          git fetch upstream
          git merge upstream/main --allow-unrelated-histories
          git push origin main
