name: Sync with upstream

on:
  schedule:
    - cron: "*/15 * * * *"  # Executa diariamente
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ConcatechOrg/black-flight-logistic
          token: ${{ secrets.GITHUBACTION }}
          path: upstream
